#!/usr/bin/env node
// Generate data/plan.yaml from a relative template + data/block.json.
// Usage:  node scripts/generate_plan.mjs [--check]
//   (default) writes data/plan.yaml
//   --check   prints the plan and exits without writing (dry run)
//
// The plan is GENERATED output. Never hand-edit data/plan.yaml — edit
// block.json or the template and rerun this. See docs/harness-architecture.md.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildPlan, WEEKDAYS } from "../lib/plan_dates.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), "utf8"));
}

// Minimal, structure-specific YAML emitter. Strings are double-quoted (JSON
// escaping is valid YAML), numbers/null bare — no dependency, no ambiguity.
function q(s) {
  return JSON.stringify(String(s));
}

function planToYaml(plan) {
  const L = [];
  L.push(`# GENERATED by scripts/generate_plan.mjs — do NOT hand-edit.`);
  L.push(`# Source: templates/${plan.plan_template}.json + data/block.json`);
  L.push(`# Regenerate:  node scripts/generate_plan.mjs`);
  L.push(`# Generated at: ${plan._generated_at}`);
  L.push("");
  L.push(`race_date: ${q(plan.race_date)}`);
  L.push(`race_name: ${q(plan.race_name)}`);
  L.push(`race_distance: ${q(plan.race_distance)}`);
  L.push(`plan: ${q(plan.plan)}`);
  L.push(`plan_template: ${q(plan.plan_template)}`);
  L.push(`plan_weeks: ${plan.plan_weeks}`);
  L.push("");
  L.push(`phases:`);
  for (const [name, weeks] of Object.entries(plan.phases)) {
    L.push(`  ${name}: [${weeks.join(", ")}]`);
  }
  L.push("");
  L.push(`weeks:`);
  for (const w of plan.weeks) {
    L.push(`  - week: ${typeof w.week === "number" ? w.week : q(w.week)}`);
    L.push(`    start_date: ${q(w.start_date)}`);
    L.push(`    end_date: ${q(w.end_date)}`);
    L.push(`    phase: ${q(w.phase)}`);
    if (w.higdon_week != null) L.push(`    higdon_week: ${w.higdon_week}`);
    if (w.note) L.push(`    note: ${q(w.note)}`);
    L.push(`    days:`);
    for (const wd of WEEKDAYS) {
      const d = w.days[wd];
      if (!d) continue;
      L.push(`      ${wd}:`);
      L.push(`        date: ${q(d.date)}`);
      L.push(`        type: ${q(d.type)}`);
      if (d.distance_km != null) L.push(`        distance_km: ${d.distance_km}`);
      if (d.duration_min != null) L.push(`        duration_min: ${d.duration_min}`);
      if (d.intervals) L.push(`        intervals: ${q(d.intervals)}`);
      if (d.race_distance) L.push(`        race_distance: ${q(d.race_distance)}`);
      if (d.notes) L.push(`        notes: ${q(d.notes)}`);
    }
  }
  L.push("");
  return L.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const block = readJson("data/block.json");
  const template = readJson(`templates/${block.plan_template}.json`);
  const plan = buildPlan(block, template);
  plan._generated_at = new Date().toISOString();
  const yaml = planToYaml(plan);

  if (check) {
    process.stdout.write(yaml);
    const higdon = plan.weeks.filter((w) => typeof w.week === "number").length;
    const travel = plan.weeks.length - higdon;
    console.error(
      `\n[check] OK — ${higdon} plan weeks + ${travel} deviation week(s); ` +
        `race ${plan.race_date}. Not written (--check).`
    );
    return;
  }

  fs.writeFileSync(path.join(ROOT, "data/plan.yaml"), yaml);
  console.log(`Wrote data/plan.yaml — ${plan.weeks.length} weeks, race ${plan.race_date}.`);
}

main();
